monolog:
    handlers:
        main:
            type: syslogudp
            host: "%papertrail_host%"
            port: "%papertrail_port%"
            level: error # whatever
            formatter: app.monolog.syslog_formatter
        nested:
            type:  rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
